spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medDesk
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:demo_data.sql